                    </div>
                </div>
                <hr>
                <div id="footer">
                    SourceForge logo copyright &#169; Open Source Technology Group<br>
                    Nazcatech logo <a id="footer-link" href="http://www.nazcatech.be" target="_blank">copyright &#169; 2004-9 Nazcatech sprl</a><br>
                    All other content <a id="footer-link" href="license.shtml">copyright &#169; 1998-2011 xlw project</a><br>
                    Graphics by Audrey Schayes and Thomas Wyngaard at <a id="footer-link" href="http://www.codefrisko.be" target="_blank">Codefrisko</a>
                </div>
                <!--/PageFooterFmt-->
            </div>
            <div class='clearfix'></div>
        </div>
        <div class='clearfix'></div>
    </div>
    <div class='clearfix'></div>
</body>
</html>
