@SETLOCAL
@IF NOT DEFINED XLW_FOUND_PROGRAMS CALL FindPrograms.bat
@IF ERRORLEVEL 1 ECHO Can't find all required programs & exit /b 1

CALL BuildProjectCpp.bat ..\xlw\examples\Example ExampleAutoGenerated
CALL BuildProjectCpp.bat ..\xlw\examples\Handwritten ExampleHandwritten
CALL BuildProjectCpp.bat ..\xlw\examples\ObjectCacheDemo ObjectCacheDemo
CALL BuildProjectCpp.bat ..\xlw\examples\C++CLR C++CLR
CALL BuildProjectCpp.bat ..\xlw\examples\LoggerDemo LoggerDemo

@ENDLOCAL