rem make -f ExampleMakefile DEV=devcpp
make -f ExampleMakefile DEV=gcc-make

"C:\Program Files (x86)\CodeBlocks\codeblocks.exe" --rebuild  --target="Debug" ..\xlw\examples\Example\codeblocks-gcc\Autogenerated.workspace  >> ExampleAutogeneratedCodeBlocks.log 2>&1 
"C:\Program Files (x86)\CodeBlocks\codeblocks.exe" --rebuild  --target="Release" ..\xlw\examples\Example\codeblocks-gcc\Autogenerated.workspace  >> ExampleAutogeneratedCodeBlocks.log 2>&1 
"C:\Program Files (x86)\Microsoft Visual Studio .NET 2003\Common7\IDE\devenv.exe"   ..\xlw\examples\Example\vc7\ExampleAutogenerated.sln  /rebuild Debug    /out ExampleAutogenerated7Debug.log
"C:\Program Files (x86)\Microsoft Visual Studio .NET 2003\Common7\IDE\devenv.exe"   ..\xlw\examples\Example\vc7\ExampleAutogenerated.sln  /rebuild Release  /out ExampleAutogenerated7Release.log
"C:\Program Files (x86)\Microsoft Visual Studio 8\VC\vcpackages\vcbuild.exe" /rebuild    ..\xlw\examples\Example\vc8\ExampleAutogenerated.sln  >> ExampleAutogenerated8.log 2>&1 
"C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\vcpackages\vcbuild.exe" /rebuild  ..\xlw\examples\Example\vc9\ExampleAutogenerated.sln  >> ExampleAutogenerated9.log 2>&1 
"C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\msbuild.exe" /p:Configuration=Release /t:rebuild  ..\xlw\examples\Example\vc10\ExampleAutogenerated.sln  >> ExampleAutogenerated10_Release.log 2>&1 
"C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\msbuild.exe" /p:Configuration=Debug /t:rebuild  ..\xlw\examples\Example\vc10\ExampleAutogenerated.sln  >> ExampleAutogenerated10_Debug.log 2>&1 
"C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\msbuild.exe" /p:Configuration=Release;Platform=x64 /t:rebuild  ..\xlw\examples\Example\vc10\ExampleAutogenerated.sln  >> ExampleAutogenerated10_Release.log 2>&1 
"C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\msbuild.exe" /p:Configuration=Debug;Platform=x64 /t:rebuild  ..\xlw\examples\Example\vc10\ExampleAutogenerated.sln  >> ExampleAutogenerated10_Debug.log 2>&1 

rem "C:\Program Files (x86)\CodeBlocks\codeblocks.exe" --rebuild  --target="Debug" ..\xlw\examples\Handwritten\codeblocks-gcc\HandWritten.workspace  >> ExampleHandWrittenCodeBlocks.log 2>&1 
rem "C:\Program Files (x86)\CodeBlocks\codeblocks.exe" --rebuild  --target="Release" ..\xlw\examples\Handwritten\codeblocks-gcc\HandWritten.workspace  >> ExampleHandWrittenCodeBlocks.log 2>&1 
"C:\Program Files (x86)\Microsoft Visual Studio .NET 2003\Common7\IDE\devenv.exe"   ..\xlw\examples\Handwritten\vc7\ExampleHandWritten.sln  /rebuild Debug    /out ExampleHandwritten7Debug.log
"C:\Program Files (x86)\Microsoft Visual Studio .NET 2003\Common7\IDE\devenv.exe"   ..\xlw\examples\Handwritten\vc7\ExampleHandWritten.sln  /rebuild Release  /out ExampleHandwritten7Release.log
"C:\Program Files (x86)\Microsoft Visual Studio 8\VC\vcpackages\vcbuild.exe" /rebuild    ..\xlw\examples\Handwritten\vc8\ExampleHandWritten.sln  >> ExampleHandwritten8.log 2>&1 
"C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\vcpackages\vcbuild.exe" /rebuild  ..\xlw\examples\Handwritten\vc9\ExampleHandWritten.sln  >> ExampleHandwritten9.log 2>&1 
"C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\msbuild.exe" /p:Configuration=Release /t:rebuild  ..\xlw\examples\Handwritten\vc10\ExampleHandWritten.sln  >> ExampleHandWritten10_Release.log 2>&1 
"C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\msbuild.exe" /p:Configuration=Debug /t:rebuild  ..\xlw\examples\Handwritten\vc10\ExampleHandWritten.sln  >> ExampleHandWritten10_Debug.log 2>&1 
"C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\msbuild.exe" /p:Configuration=Release;Platform=x64 /t:rebuild  ..\xlw\examples\Handwritten\vc10\ExampleHandWritten.sln  >> ExampleHandWritten10_Release.log 2>&1 
"C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\msbuild.exe" /p:Configuration=Debug;Platform=x64 /t:rebuild  ..\xlw\examples\Handwritten\vc10\ExampleHandWritten.sln  >> ExampleHandWritten10_Debug.log 2>&1 


"C:\Program Files (x86)\CodeBlocks\codeblocks.exe" --rebuild  --target="Debug" ..\xlw\examples\ObjectCacheDemo\codeblocks-gcc\ObjectCacheDemo.workspace  >> ObjectCacheDemoCodeBlocks.log 2>&1 
"C:\Program Files (x86)\CodeBlocks\codeblocks.exe" --rebuild  --target="Release" ..\xlw\examples\ObjectCacheDemo\codeblocks-gcc\ObjectCacheDemo.workspace  >> ObjectCacheDemoCodeBlocks.log 2>&1 
"C:\Program Files (x86)\Microsoft Visual Studio .NET 2003\Common7\IDE\devenv.exe"   ..\xlw\examples\ObjectCacheDemo\vc7\ObjectCacheDemo.sln  /rebuild Debug    /out ObjectCacheDemo7Debug.log
"C:\Program Files (x86)\Microsoft Visual Studio .NET 2003\Common7\IDE\devenv.exe"   ..\xlw\examples\ObjectCacheDemo\vc7\ObjectCacheDemo.sln  /rebuild Release  /out ObjectCacheDemo7Release.log
"C:\Program Files (x86)\Microsoft Visual Studio 8\VC\vcpackages\vcbuild.exe" /rebuild    ..\xlw\examples\ObjectCacheDemo\vc8\ObjectCacheDemo.sln  >> ObjectCacheDemo8.log 2>&1 
"C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\vcpackages\vcbuild.exe" /rebuild  ..\xlw\examples\ObjectCacheDemo\vc9\ObjectCacheDemo.sln  >> ObjectCacheDemo9.log 2>&1 
"C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\msbuild.exe" /p:Configuration=Release /t:rebuild  ..\xlw\examples\ObjectCacheDemo\vc10\ObjectCacheDemo.sln  >> ObjectCacheDemo10_Release.log 2>&1 
"C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\msbuild.exe" /p:Configuration=Debug /t:rebuild  ..\xlw\examples\ObjectCacheDemo\vc10\ObjectCacheDemo.sln  >> ObjectCacheDemo10_Debug.log 2>&1 
"C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\msbuild.exe" /p:Configuration=Release;Platform=x64 /t:rebuild  ..\xlw\examples\ObjectCacheDemo\vc10\ObjectCacheDemo.sln  >> ObjectCacheDemo10_Release.log 2>&1 
"C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\msbuild.exe" /p:Configuration=Debug;Platform=x64 /t:rebuild  ..\xlw\examples\ObjectCacheDemo\vc10\ObjectCacheDemo.sln  >> ObjectCacheDemo10_Debug.log 2>&1 

