//// 
//// Autogenerated by xlw 
//// Do not edit this file, it will be overwritten 
//// by InterfaceGenerator 
////

#include <xlw/MyContainers.h>
#include <xlw/CellMatrix.h>
#include "cppinterface.h"
#include <xlw/xlw.h>
#include <xlw/XlFunctionRegistration.h>
#include <stdexcept>
#include <xlw/XlOpenClose.h>
#include <ctime>
namespace {
const char* LibraryName = "cpp_clr_Template";
};


// registrations start here


namespace
{
XLRegistration::Arg
GetHistoricDataFromYahooArgs[]=
{
{ "symbol"," Yahoo Symbol ","XLF_OPER"},
{ "beginDate"," Begin Date ","B"},
{ "endDate","End Date ","B"}
};
  XLRegistration::XLFunctionRegistrationHelper
registerGetHistoricDataFromYahoo("xlGetHistoricDataFromYahoo",
"GetHistoricDataFromYahoo",
" Obtains historial market data from yahoo ",
LibraryName,
GetHistoricDataFromYahooArgs,
3
,false
,false
,""
,""
,false
,false
,false
);
}



extern "C"
{
LPXLFOPER EXCEL_EXPORT
xlGetHistoricDataFromYahoo(
LPXLFOPER symbola,
double beginDate,
double endDate)
{
EXCEL_BEGIN;

	if (XlfExcel::Instance().IsCalledByFuncWiz())
		return XlfOper(true);

XlfOper symbolb(
	(symbola));
std::string symbol(
	symbolb.AsString("symbol"));



CellMatrix result(
	GetHistoricDataFromYahoo(
		symbol,
		beginDate,
		endDate)
	);
return XlfOper(result);
EXCEL_END
}
}



//////////////////////////

