//// 
//// Autogenerated by xlw 
//// Do not edit this file, it will be overwritten 
//// by InterfaceGenerator 
////

#include <xlw/MyContainers.h>
#include <xlw/CellMatrix.h>
#include "cppinterface.h"
#include <xlw/xlw.h>
#include <xlw/XlFunctionRegistration.h>
#include <stdexcept>
#include <xlw/XlOpenClose.h>
#include <ctime>
namespace {
const char* LibraryName = "cpp_clr_Template";
};


// registrations start here


namespace
{
XLRegistration::Arg
CPlusPlusFunctionArgs[]=
{
 { "","" } 
};
  XLRegistration::XLFunctionRegistrationHelper
registerCPlusPlusFunction("xlCPlusPlusFunction",
"CPlusPlusFunction",
" C++ Function ",
LibraryName,
CPlusPlusFunctionArgs,
0
,false
,false
,""
,""
,false
,false
,false
);
}



extern "C"
{
LPXLFOPER EXCEL_EXPORT
xlCPlusPlusFunction(
)
{
EXCEL_BEGIN;

    if (XlfExcel::Instance().IsCalledByFuncWiz())
        return XlfOper(true);

std::string result(
    CPlusPlusFunction());
return XlfOper(result);
EXCEL_END
}
}



//////////////////////////

